name: Deploy Rust Project Based on Tag

on:
  push:
    tags:
      - '*beta*'

env:
  EXECUTABLE_FILE_NAME: "quackers-ws-server"

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.7.0
        with:
          ssh-private-key: ${{ secrets.SERVER_SSH_KEY }}

      - name: Set up Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable  # You can also use nightly or a specific version

      - name: Navigate Into ws-server Directory
        run: cd ws-server

      - name: Ls
        run: ls

      - name: Install dependencies & Build
        run: cd ws-server && cargo build --release

      - name: Run tests
        run: cd ws-server && cargo test --release

      - name: Run clippy
        run: cd ws-server && cargo clippy --release

      - name: Add server to known_hosts
        run: |
          ssh-keyscan -H ${{ secrets.SERVER_IP_ADDRESS }} >> ~/.ssh/known_hosts

      - name: Copy Executable to on_deck folder 
        run: scp -r ./ws-server/target/release/$EXECUTABLE_FILE_NAME root@${{ secrets.SERVER_IP_ADDRESS }}:/root/on_deck/

      - name: Run deploy bash file
        run: ssh -o BatchMode=yes root@${{ secrets.SERVER_IP_ADDRESS }} '/root/quackers_deploy.sh'

      - name: Print finished
        run: echo "Deployed!"
